apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips
  labels:
    name: parsec-vips
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_vips
        name: parsec-vips
        #resources:
        #    limits:
        #        cpu: "3"
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 4,5,6,7 ./run -a run -S parsec -p vips -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
         cca-project-nodetype: "node-c-8core"
